const PRODUCT = {
  id: "",
  title: "",
  handle: "",
  subtitle: null,
  description: "",
  is_giftcard: false,
  status: "",
  thumbnail: "",
  weight: "",
  length: null,
  height: null,
  width: null,
  origin_country: null,
  hs_code: null,
  mid_code: null,
  material: null,
  discountable: true,
  external_id: null,
  type_id: null,
  type: null,
  collection_id: null,
  collection: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const CUSTOMER = {
  id: "",
  company_name: null,
  first_name: "",
  last_name: "",
  email: "",
  phone: "",
  has_account: false,
  created_by: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
};
const ORDER = {
  id: "",
  display_id: 445,
  region_id: "",
  customer_id: "",
  version: 2,
  sales_channel_id: "",
  status: "",
  is_draft_order: false,
  email: "",
  currency_code: "",
  no_notification: false,
  canceled_at: null,
  shipping_address: {
    id: "",
  },
  billing_address: {
    id: "",
  },
  created_at: "",
  updated_at: "",
  deleted_at: null,
  shipping_address_id: "",
  billing_address_id: "",
};
const CART = {
  id: "",
  region_id: "",
  customer_id: "",
  sales_channel_id: "",
  email: "",
  currency_code: "",
  completed_at: null,
  shipping_address: {
    id: "",
  },
  billing_address: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
  shipping_address_id: "",
};

const PRODUCT_CATEGORY = {
  id: "",
  name: "",
  description: "",
  handle: "",
  mpath: "",
  is_active: true,
  is_internal: false,
  rank: 2,
  parent_category: null,
  created_at: "",
  updated_at: "",
};
const PRODUCT_COLLECTION = {
  id: "",
  title: "",
  handle: "",
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const PRODUCT_OPTION = {
  id: "",
  title: "",
  product_id: "",
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const PRODUCT_TAG = {
  id: "",
  value: "",
  created_at: "",
  updated_at: "",
  deleted_at: null,
};
const PRODUCT_TYPE = {
  id: "",
  value: "",
  metadata: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
  products: [],
};

const PRODUCT_VARIANT = {
  id: "",
  title: "",
  sku: "",
  barcode: null,
  ean: null,
  upc: null,
  allow_backorder: false,
  manage_inventory: true,
  hs_code: null,
  origin_country: null,
  mid_code: null,
  material: null,
  weight: null,
  length: null,
  height: null,
  width: null,
  metadata: null,
  variant_rank: 0,
  product_id: "",
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const REGION = {
  id: "",
  name: "",
  currency_code: "",
  automatic_taxes: true,
  metadata: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const SALES_CHANNEL = {
  id: "",
  name: "",
  description: "",
  is_disabled: false,
  metadata: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const USER = {
  id: "",
  first_name: null,
  last_name: null,
  email: "",
  avatar_url: null,
  metadata: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const PAYMENT = {
  id: "",
  currency_code: "",
  provider_id: "",
  data: {},
  metadata: null,
  captured_at: "",
  canceled_at: null,
  payment_collection_id: "",
  payment_collection: {
    id: "",
    currency_code: "",
    completed_at: null,
    status: "",
    metadata: null,
    raw_amount: {
      value: "",
      precision:0,
    },
    raw_authorized_amount: {
      value: "",
      precision: 0,
    },
    raw_captured_amount: {
      value: "",
      precision: 0,
    },
    raw_refunded_amount: {
      value: "",
      precision: 0,
    },
    created_at: "",
    updated_at: "",
    deleted_at: null,
    payment_providers: [],
    payment_sessions: [
      {
        id: "",
        currency_code: "",
        provider_id: "",
        data: {},
        context: null,
        status: "",
        authorized_at: "",
        payment_collection_id: "",
        metadata: null,
        raw_amount: {
          value: "",
          precision: 0,
        },
        created_at: "",
        updated_at: "",
        deleted_at: null,
        amount: 0,
      },
    ],
    amount: 0,
    authorized_amount: 0,
    captured_amount: 0,
    refunded_amount: 0,
  },
  payment_session: {
    id: "",
    currency_code: "",
    provider_id: "",
    data: {},
    context: null,
    status: "",
    authorized_at: "",
    payment_collection_id: "",
    payment_collection: {
      id: "",
      currency_code: "",
      completed_at: null,
      status: "",
      metadata: null,
      raw_amount: {
        value: "",
        precision: 0,
      },
      raw_authorized_amount: {
        value: "",
        precision: 0,
      },
      raw_captured_amount: {
        value: "",
        precision: 0,
      },
      raw_refunded_amount: {
        value: "",
        precision: 0,
      },
      created_at: "",
      updated_at: "",
      deleted_at: null,
      payment_providers: [],
      amount: 0,
      authorized_amount: 0,
      captured_amount: 0,
      refunded_amount: 0,
    },
    metadata: null,
    raw_amount: {
      value: "",
      precision: 0,
    },
    created_at: "",
    updated_at: "",
    deleted_at: null,
    amount: 0,
  },
  raw_amount: {
    value: "",
    precision: 0,
  },
  created_at: "",
  updated_at: "",
  deleted_at: null,
  payment_session_id: "",
  refunds: [],
  captures: [
    {
      id: "",
      payment_id: "",
      metadata: null,
      created_by: null,
      raw_amount: {
        value: "",
        precision: 0,
      },
      created_at: "",
      updated_at: "",
      deleted_at: null,
      amount: 0,
    },
  ],
  amount: 0,
};

const NOTIFICATION_EVENTS = [
  // { id: 1, name: "auth.password_reset", tags: {} },
  { id: 2, name: "cart.created", tags: CART },
  { id: 3, name: "cart.updated", tags: CART },
  { id: 4, name: "cart.region_updated", tags: CART },
  { id: 5, name: "customer.created", tags: CUSTOMER },
  { id: 6, name: "customer.updated", tags: CUSTOMER },
  { id: 7, name: "customer.deleted", tags: CUSTOMER },
  // { id: 8, name: "shipment.created", tags: {} },
  // { id: 9, name: "delivery.created", tags: {} },
  // { id: 10, name: "invite.accepted", tags: {} },
  // { id: 11, name: "invite.created", tags: {} },
  // { id: 12, name: "invite.deleted", tags: {} },
  // { id: 13, name: "invite.resent", tags: {} },
  { id: 14, name: "order.updated", tags: ORDER },
  { id: 15, name: "order.placed", tags: ORDER },
  { id: 16, name: "order.canceled", tags: ORDER },
  { id: 17, name: "order.completed", tags: ORDER },
  { id: 18, name: "order.archived", tags: ORDER },
  //
  { id: 19, name: "order.fulfillment_created", tags: ORDER },
  { id: 20, name: "order.fulfillment_canceled", tags: ORDER },
  { id: 21, name: "order.return_requested", tags: ORDER },
  { id: 22, name: "order.return_received", tags: ORDER },
  { id: 23, name: "order.claim_created", tags: ORDER },
  { id: 24, name: "order.exchange_created", tags: ORDER },
  { id: 25, name: "order.transfer_requested", tags: ORDER },
  //
  { id: 26, name: "product.created", tags: PRODUCT },
  { id: 27, name: "product.updated", tags: PRODUCT },
  { id: 28, name: "product.deleted", tags: PRODUCT },
  { id: 29, name: "product-category.created", tags: PRODUCT_CATEGORY },
  { id: 30, name: "product-category.updated", tags: PRODUCT_CATEGORY },
  { id: 31, name: "product-category.deleted", tags: PRODUCT_CATEGORY },
  { id: 32, name: "product-collection.created", tags: PRODUCT_COLLECTION },
  { id: 33, name: "product-collection.updated", tags: PRODUCT_COLLECTION },
  { id: 34, name: "product-collection.deleted", tags: PRODUCT_COLLECTION },
  { id: 35, name: "product-option.created", tags: PRODUCT_OPTION },
  { id: 36, name: "product-option.updated", tags: PRODUCT_OPTION },
  { id: 37, name: "product-option.deleted", tags: PRODUCT_OPTION },
  { id: 38, name: "product-tag.created", tags: PRODUCT_TAG },
  { id: 39, name: "product-tag.updated", tags: PRODUCT_TAG },
  { id: 40, name: "product-tag.deleted", tags: PRODUCT_TAG },
  { id: 41, name: "product-type.created", tags: PRODUCT_TYPE },
  { id: 42, name: "product-type.updated", tags: PRODUCT_TYPE },
  { id: 43, name: "product-type.deleted", tags: PRODUCT_TYPE },
  { id: 44, name: "product-variant.created", tags: PRODUCT_VARIANT },
  { id: 45, name: "product-variant.updated", tags: PRODUCT_VARIANT },
  { id: 46, name: "product-variant.deleted", tags: PRODUCT_VARIANT },
  { id: 47, name: "region.created", tags: REGION },
  { id: 48, name: "region.updated", tags: REGION },
  { id: 49, name: "region.deleted", tags: REGION },
  { id: 50, name: "sales-channel.created", tags: SALES_CHANNEL },
  { id: 51, name: "sales-channel.updated", tags: SALES_CHANNEL },
  { id: 52, name: "sales-channel.deleted", tags: SALES_CHANNEL },
  { id: 53, name: "user.created", tags: USER },
  { id: 54, name: "user.updated", tags: USER },
  { id: 55, name: "user.deleted", tags: USER },
  { id: 56, name: "payment.captured", tags: PAYMENT },
  { id: 57, name: "payment.refunded", tags: PAYMENT },
];
export { NOTIFICATION_EVENTS };
