const PRODUCT = {
  id: "",
  title: "",
  handle: "",
  subtitle: null,
  description: "",
  is_giftcard: false,
  status: "",
  thumbnail: "",
  weight: "",
  length: null,
  height: null,
  width: null,
  origin_country: null,
  hs_code: null,
  mid_code: null,
  material: null,
  discountable: true,
  external_id: null,
  type_id: null,
  type: null,
  collection_id: null,
  collection: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const CUSTOMER = {
  id: "",
  company_name: null,
  first_name: "",
  last_name: "",
  email: "",
  phone: "",
  has_account: false,
  created_by: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
};
const ORDER = {
  id: "",
  display_id: 445,
  region_id: "",
  customer_id: "",
  version: 2,
  sales_channel_id: "",
  status: "",
  is_draft_order: false,
  email: "",
  currency_code: "",
  no_notification: false,
  canceled_at: null,
  shipping_address: {
    id: "",
  },
  billing_address: {
    id: "",
  },
  created_at: "",
  updated_at: "",
  deleted_at: null,
  shipping_address_id: "",
  billing_address_id: "",
};
const CART = {
  id: "",
  region_id: "",
  customer_id: "",
  sales_channel_id: "",
  email: "",
  currency_code: "",
  completed_at: null,
  shipping_address: {
    id: "",
  },
  billing_address: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
  shipping_address_id: "",
};

const PRODUCT_CATEGORY = {
  id: "",
  name: "",
  description: "",
  handle: "",
  mpath: "",
  is_active: true,
  is_internal: false,
  rank: 2,
  parent_category: null,
  created_at: "",
  updated_at: "",
};
const PRODUCT_COLLECTION = {
  id: "",
  title: "",
  handle: "",
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const PRODUCT_OPTION = {
  id: "",
  title: "",
  product_id: "",
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const PRODUCT_TAG = {
  id: "",
  value: "",
  created_at: "",
  updated_at: "",
  deleted_at: null,
};
const PRODUCT_TYPE = {
  id: "",
  value: "",
  metadata: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
  products: [],
};

const PRODUCT_VARIANT = {
  id: "",
  title: "",
  sku: "",
  barcode: null,
  ean: null,
  upc: null,
  allow_backorder: false,
  manage_inventory: true,
  hs_code: null,
  origin_country: null,
  mid_code: null,
  material: null,
  weight: null,
  length: null,
  height: null,
  width: null,
  metadata: null,
  variant_rank: 0,
  product_id: "",
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const REGION = {
  id: "",
  name: "",
  currency_code: "",
  automatic_taxes: true,
  metadata: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const SALES_CHANNEL = {
  id: "",
  name: "",
  description: "",
  is_disabled: false,
  metadata: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const USER = {
  id: "",
  first_name: null,
  last_name: null,
  email: "",
  avatar_url: null,
  metadata: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
};

const PAYMENT = {
  id: "pay_01JGZRZS54VNM9CMYD2SNEK3VP",
  currency_code: "mur",
  provider_id: "pp_system_default",
  data: {},
  metadata: null,
  captured_at: "2025-01-07T06:59:42.526Z",
  canceled_at: null,
  payment_collection_id: "pay_col_01JGZRZS2E2CHRDKJ8B4HWB9GK",
  payment_collection: {
    id: "pay_col_01JGZRZS2E2CHRDKJ8B4HWB9GK",
    currency_code: "mur",
    completed_at: null,
    status: "authorized",
    metadata: null,
    raw_amount: {
      value: "410",
      precision: 20,
    },
    raw_authorized_amount: {
      value: "410",
      precision: 20,
    },
    raw_captured_amount: {
      value: "410",
      precision: 20,
    },
    raw_refunded_amount: {
      value: "0",
      precision: 20,
    },
    created_at: "2025-01-07T06:59:42.286Z",
    updated_at: "2025-01-07T06:59:42.601Z",
    deleted_at: null,
    payment_providers: [],
    payment_sessions: [
      {
        id: "payses_01JGZRZS31034T14E9E6NDBT4V",
        currency_code: "mur",
        provider_id: "pp_system_default",
        data: {},
        context: null,
        status: "authorized",
        authorized_at: "2025-01-07T06:59:42.370Z",
        payment_collection_id: "pay_col_01JGZRZS2E2CHRDKJ8B4HWB9GK",
        metadata: null,
        raw_amount: {
          value: "410",
          precision: 20,
        },
        created_at: "2025-01-07T06:59:42.305Z",
        updated_at: "2025-01-07T06:59:42.372Z",
        deleted_at: null,
        amount: 410,
      },
    ],
    amount: 410,
    authorized_amount: 410,
    captured_amount: 410,
    refunded_amount: 0,
  },
  payment_session: {
    id: "payses_01JGZRZS31034T14E9E6NDBT4V",
    currency_code: "mur",
    provider_id: "pp_system_default",
    data: {},
    context: null,
    status: "authorized",
    authorized_at: "2025-01-07T06:59:42.370Z",
    payment_collection_id: "pay_col_01JGZRZS2E2CHRDKJ8B4HWB9GK",
    payment_collection: {
      id: "pay_col_01JGZRZS2E2CHRDKJ8B4HWB9GK",
      currency_code: "mur",
      completed_at: null,
      status: "authorized",
      metadata: null,
      raw_amount: {
        value: "410",
        precision: 20,
      },
      raw_authorized_amount: {
        value: "410",
        precision: 20,
      },
      raw_captured_amount: {
        value: "410",
        precision: 20,
      },
      raw_refunded_amount: {
        value: "0",
        precision: 20,
      },
      created_at: "2025-01-07T06:59:42.286Z",
      updated_at: "2025-01-07T06:59:42.601Z",
      deleted_at: null,
      payment_providers: [],
      amount: 410,
      authorized_amount: 410,
      captured_amount: 410,
      refunded_amount: 0,
    },
    metadata: null,
    raw_amount: {
      value: "410",
      precision: 20,
    },
    created_at: "2025-01-07T06:59:42.305Z",
    updated_at: "2025-01-07T06:59:42.372Z",
    deleted_at: null,
    amount: 410,
  },
  raw_amount: {
    value: "410",
    precision: 20,
  },
  created_at: "2025-01-07T06:59:42.372Z",
  updated_at: "2025-01-07T06:59:42.529Z",
  deleted_at: null,
  payment_session_id: "payses_01JGZRZS31034T14E9E6NDBT4V",
  refunds: [],
  captures: [
    {
      id: "capt_01JGZRZS9TPFQFCBCZSVNST9XR",
      payment_id: "pay_01JGZRZS54VNM9CMYD2SNEK3VP",
      metadata: null,
      created_by: null,
      raw_amount: {
        value: "410",
        precision: 20,
      },
      created_at: "2025-01-07T06:59:42.522Z",
      updated_at: "2025-01-07T06:59:42.522Z",
      deleted_at: null,
      amount: 410,
    },
  ],
  amount: 410,
};

const NOTIFICATION_EVENTS = [
  // { id: 1, name: "auth.password_reset", tags: {} },
  { id: 2, name: "cart.created", tags: CART },
  { id: 3, name: "cart.updated", tags: CART },
  { id: 4, name: "cart.region_updated", tags: CART },
  { id: 5, name: "customer.created", tags: CUSTOMER },
  { id: 6, name: "customer.updated", tags: CUSTOMER },
  { id: 7, name: "customer.deleted", tags: CUSTOMER },
  // { id: 8, name: "shipment.created", tags: {} },
  // { id: 9, name: "delivery.created", tags: {} },
  // { id: 10, name: "invite.accepted", tags: {} },
  // { id: 11, name: "invite.created", tags: {} },
  // { id: 12, name: "invite.deleted", tags: {} },
  // { id: 13, name: "invite.resent", tags: {} },
  { id: 14, name: "order.updated", tags: ORDER },
  { id: 15, name: "order.placed", tags: ORDER },
  { id: 16, name: "order.canceled", tags: ORDER },
  { id: 17, name: "order.completed", tags: ORDER },
  { id: 18, name: "order.archived", tags: ORDER },
  //
  { id: 19, name: "order.fulfillment_created", tags: ORDER },
  { id: 20, name: "order.fulfillment_canceled", tags: ORDER },
  { id: 21, name: "order.return_requested", tags: ORDER },
  { id: 22, name: "order.return_received", tags: ORDER },
  { id: 23, name: "order.claim_created", tags: ORDER },
  { id: 24, name: "order.exchange_created", tags: ORDER },
  { id: 25, name: "order.transfer_requested", tags: ORDER },
  //
  { id: 26, name: "product.created", tags: PRODUCT },
  { id: 27, name: "product.updated", tags: PRODUCT },
  { id: 28, name: "product.deleted", tags: PRODUCT },
  { id: 29, name: "product-category.created", tags: PRODUCT_CATEGORY },
  { id: 30, name: "product-category.updated", tags: PRODUCT_CATEGORY },
  { id: 31, name: "product-category.deleted", tags: PRODUCT_CATEGORY },
  { id: 32, name: "product-collection.created", tags: PRODUCT_COLLECTION },
  { id: 33, name: "product-collection.updated", tags: PRODUCT_COLLECTION },
  { id: 34, name: "product-collection.deleted", tags: PRODUCT_COLLECTION },
  { id: 35, name: "product-option.created", tags: PRODUCT_OPTION },
  { id: 36, name: "product-option.updated", tags: PRODUCT_OPTION },
  { id: 37, name: "product-option.deleted", tags: PRODUCT_OPTION },
  { id: 38, name: "product-tag.created", tags: PRODUCT_TAG },
  { id: 39, name: "product-tag.updated", tags: PRODUCT_TAG },
  { id: 40, name: "product-tag.deleted", tags: PRODUCT_TAG },
  { id: 41, name: "product-type.created", tags: PRODUCT_TYPE },
  { id: 42, name: "product-type.updated", tags: PRODUCT_TYPE },
  { id: 43, name: "product-type.deleted", tags: PRODUCT_TYPE },
  { id: 44, name: "product-variant.created", tags: PRODUCT_VARIANT },
  { id: 45, name: "product-variant.updated", tags: PRODUCT_VARIANT },
  { id: 46, name: "product-variant.deleted", tags: PRODUCT_VARIANT },
  { id: 47, name: "region.created", tags: REGION },
  { id: 48, name: "region.updated", tags: REGION },
  { id: 49, name: "region.deleted", tags: REGION },
  { id: 50, name: "sales-channel.created", tags: SALES_CHANNEL },
  { id: 51, name: "sales-channel.updated", tags: SALES_CHANNEL },
  { id: 52, name: "sales-channel.deleted", tags: SALES_CHANNEL },
  { id: 53, name: "user.created", tags: USER },
  { id: 54, name: "user.updated", tags: USER },
  { id: 55, name: "user.deleted", tags: USER },
  { id: 56, name: "payment.captured", tags: PAYMENT },
  { id: 57, name: "payment.refunded", tags: PAYMENT },
];
export { NOTIFICATION_EVENTS };
