const PRODUCT_CREATED = {
  id: "string",
  title: "string",
  handle: "string",
  description: "string",
  is_giftcard: "boolean",
  status: "string",
  metadata: {
    expiryDay: "string",
  },
  variants: [
    {
      id: "string",
      title: "string",
      allow_backorder: "boolean",
      manage_inventory: "boolean",
      options: [
        {
          id: "string",
          value: "string",
          option_id: "string",
        },
      ],
    },
  ],
};
const CUSTOMER_CREATED = {
  id: "string",
  company_name: "string",
  first_name: "string",
  last_name: "string",
  email: "string",
  phone: "string",
  created_at: "string",
  updated_at: "string",
  deleted_at: null,
  addresses: [
    {
      id: "string",
      address_name: "string",
      is_default_shipping: true,
      is_default_billing: true,
      customer_id: "string",
      company: "string",
      first_name: "string",
      last_name: "string",
      address_1: "string",
      address_2: "string",
      city: "string",
      country_code: "usd",
      province: "string",
      postal_code: "string",
      phone: "string",
      metadata: {},
      created_at: "2019-08-24T14:15:22Z",
      updated_at: "2019-08-24T14:15:22Z",
    },
  ],
};

const NOTIFICATION_EVENTS = [
  { id: 1, name: "auth.password_reset", tags: {} },
  { id: 2, name: "cart.created", tags: {} },
  { id: 3, name: "cart.updated", tags: {} },
  { id: 4, name: "cart.region_updated", tags: {} },
  { id: 5, name: "customer.created", tags: CUSTOMER_CREATED },
  { id: 6, name: "customer.updated", tags: CUSTOMER_CREATED },
  { id: 7, name: "customer.deleted", tags: CUSTOMER_CREATED },
  { id: 8, name: "shipment.created", tags: {} },
  { id: 9, name: "delivery.created", tags: {} },
  { id: 10, name: "invite.accepted", tags: {} },
  { id: 11, name: "invite.created", tags: {} },
  { id: 12, name: "invite.deleted", tags: {} },
  { id: 13, name: "invite.resent", tags: {} },
  { id: 14, name: "order.updated", tags: {} },
  { id: 15, name: "order.placed", tags: {} },
  { id: 16, name: "order.canceled", tags: {} },
  { id: 17, name: "order.completed", tags: {} },
  { id: 18, name: "order.archived", tags: {} },
  { id: 19, name: "order.fulfillment_created", tags: {} },
  { id: 20, name: "order.fulfillment_canceled", tags: {} },
  { id: 21, name: "order.return_requested", tags: {} },
  { id: 22, name: "order.return_received", tags: {} },
  { id: 23, name: "order.claim_created", tags: {} },
  { id: 24, name: "order.exchange_created", tags: {} },
  { id: 25, name: "order.transfer_requested", tags: {} },
  { id: 26, name: "product.created", tags: PRODUCT_CREATED },
  { id: 27, name: "product.updated", tags: PRODUCT_CREATED },
  { id: 28, name: "product.deleted", tags: PRODUCT_CREATED },
  { id: 29, name: "product-category.created", tags: {} },
  { id: 30, name: "product-category.updated", tags: {} },
  { id: 31, name: "product-category.deleted", tags: {} },
  { id: 32, name: "product-collection.created", tags: {} },
  { id: 33, name: "product-collection.updated", tags: {} },
  { id: 34, name: "product-collection.deleted", tags: {} },
  { id: 35, name: "product-option.created", tags: {} },
  { id: 36, name: "product-option.updated", tags: {} },
  { id: 37, name: "product-option.deleted", tags: {} },
  { id: 38, name: "product-tag.created", tags: {} },
  { id: 39, name: "product-tag.updated", tags: {} },
  { id: 40, name: "product-tag.deleted", tags: {} },
  { id: 41, name: "product-type.created", tags: {} },
  { id: 42, name: "product-type.updated", tags: {} },
  { id: 43, name: "product-type.deleted", tags: {} },
  { id: 44, name: "product-variant.created", tags: {} },
  { id: 45, name: "product-variant.updated", tags: {} },
  { id: 46, name: "product-variant.deleted", tags: {} },
  { id: 47, name: "region.created", tags: {} },
  { id: 48, name: "region.updated", tags: {} },
  { id: 49, name: "region.deleted", tags: {} },
  { id: 50, name: "sales-channel.created", tags: {} },
  { id: 51, name: "sales-channel.updated", tags: {} },
  { id: 52, name: "sales-channel.deleted", tags: {} },
  { id: 53, name: "user.created", tags: {} },
  { id: 54, name: "user.updated", tags: {} },
  { id: 55, name: "user.deleted", tags: {} },
  { id: 56, name: "payment.captured", tags: {} },
  { id: 57, name: "payment.refunded", tags: {} },
];
export { NOTIFICATION_EVENTS };
