const PRODUCT_CREATED = {
  id: "prod_01JP20B5KRZHBTYZV3WT2K2P2S",
  title: "Medusa Sweatpants",
  handle: "sweatpants",
  subtitle: "hello0",
  description:
    "Reimagine the feeling of classic sweatpants. With our cotton sweatpants, everyday essentials no longer have to be ordinary.",
  is_giftcard: false,
  status: "published",
  thumbnail:
    "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png",
  weight: "400",
  length: null,
  height: null,
  width: null,
  origin_country: null,
  hs_code: null,
  mid_code: null,
  material: null,
  discountable: true,
  external_id: null,
  metadata: null,
  type_id: null,
  type: null,
  collection_id: null,
  collection: null,
  created_at: "2025-03-11T07:05:13.596Z",
  updated_at: "2025-03-11T07:05:13.596Z",
  deleted_at: null,
};
const CUSTOMER_CREATED = {
  id: "cus_01JP2MWPQCH37SXC1WSG70AHR3",
  company_name: "wrvwrwv",
  first_name: "wrvwr",
  last_name: "rwvwrv",
  email: "harzh.patel@gmail.com",
  phone: null,
  has_account: false,
  metadata: null,
  created_by: "user_01JP20AXEJ2P69175ZM6VNVBQX",
  created_at: "2025-03-11T13:04:19.693Z",
  updated_at: "2025-03-11T13:04:19.693Z",
  deleted_at: null,
  groups: [],
  addresses: [],
};

const NOTIFICATION_EVENTS = [
  { id: 1, name: "auth.password_reset", tags: {} },
  { id: 2, name: "cart.created", tags: {} },
  { id: 3, name: "cart.updated", tags: {} },
  { id: 4, name: "cart.region_updated", tags: {} },
  { id: 5, name: "customer.created", tags: CUSTOMER_CREATED },
  { id: 6, name: "customer.updated", tags: CUSTOMER_CREATED },
  { id: 7, name: "customer.deleted", tags: CUSTOMER_CREATED },
  { id: 8, name: "shipment.created", tags: {} },
  { id: 9, name: "delivery.created", tags: {} },
  { id: 10, name: "invite.accepted", tags: {} },
  { id: 11, name: "invite.created", tags: {} },
  { id: 12, name: "invite.deleted", tags: {} },
  { id: 13, name: "invite.resent", tags: {} },
  { id: 14, name: "order.updated", tags: {} },
  { id: 15, name: "order.placed", tags: {} },
  { id: 16, name: "order.canceled", tags: {} },
  { id: 17, name: "order.completed", tags: {} },
  { id: 18, name: "order.archived", tags: {} },
  { id: 19, name: "order.fulfillment_created", tags: {} },
  { id: 20, name: "order.fulfillment_canceled", tags: {} },
  { id: 21, name: "order.return_requested", tags: {} },
  { id: 22, name: "order.return_received", tags: {} },
  { id: 23, name: "order.claim_created", tags: {} },
  { id: 24, name: "order.exchange_created", tags: {} },
  { id: 25, name: "order.transfer_requested", tags: {} },
  { id: 26, name: "product.created", tags: PRODUCT_CREATED },
  { id: 27, name: "product.updated", tags: PRODUCT_CREATED },
  { id: 28, name: "product.deleted", tags: PRODUCT_CREATED },
  { id: 29, name: "product-category.created", tags: {} },
  { id: 30, name: "product-category.updated", tags: {} },
  { id: 31, name: "product-category.deleted", tags: {} },
  { id: 32, name: "product-collection.created", tags: {} },
  { id: 33, name: "product-collection.updated", tags: {} },
  { id: 34, name: "product-collection.deleted", tags: {} },
  { id: 35, name: "product-option.created", tags: {} },
  { id: 36, name: "product-option.updated", tags: {} },
  { id: 37, name: "product-option.deleted", tags: {} },
  { id: 38, name: "product-tag.created", tags: {} },
  { id: 39, name: "product-tag.updated", tags: {} },
  { id: 40, name: "product-tag.deleted", tags: {} },
  { id: 41, name: "product-type.created", tags: {} },
  { id: 42, name: "product-type.updated", tags: {} },
  { id: 43, name: "product-type.deleted", tags: {} },
  { id: 44, name: "product-variant.created", tags: {} },
  { id: 45, name: "product-variant.updated", tags: {} },
  { id: 46, name: "product-variant.deleted", tags: {} },
  { id: 47, name: "region.created", tags: {} },
  { id: 48, name: "region.updated", tags: {} },
  { id: 49, name: "region.deleted", tags: {} },
  { id: 50, name: "sales-channel.created", tags: {} },
  { id: 51, name: "sales-channel.updated", tags: {} },
  { id: 52, name: "sales-channel.deleted", tags: {} },
  { id: 53, name: "user.created", tags: {} },
  { id: 54, name: "user.updated", tags: {} },
  { id: 55, name: "user.deleted", tags: {} },
  { id: 56, name: "payment.captured", tags: {} },
  { id: 57, name: "payment.refunded", tags: {} },
];
export { NOTIFICATION_EVENTS };
